#Повседневные
words_d = [
('пока', 'goodbye'),
('привет', 'hello'),
('помогите', 'help'),
('один', 'one'),
('два', 'two'),
('три', 'three'),
('четыре', 'four'),
('пять', 'five'),
('шесть', 'six'),
('семь', 'seven'),
('восемь', 'eight'),
('девять', 'nine'),
('десять', 'ten'),
('сотня', 'hundred'),
('тысяча', 'thousand'),
('миллион', 'million'),
('миллиард', 'billion'),
('одинадцать', 'eleven'),
('понимать', 'understand'),
('после', 'after'),
('прямо', 'straight'),
('разбудить', 'wake'),
('до', 'before'),
('сейчас', 'now'),
('рюкзак', 'backpack'),
('счет', 'account'),
('действия', 'act'),
('дополнение', 'addition'),
('регулировать', 'adjust'),
('реклама', 'advertisement'),
('соглашение', 'agreement'),
('воздух', 'air'),
('количество', 'amount'),
('развлечение', 'amusement'),
('животное', 'animal'),
('ответ', 'answer'),
('аппарат', 'apparatus'),
('одобрение', 'approval'),
('спор', 'argument'),
('искусство', 'art'),
('нападение', 'attack'),
('попытка', 'attempt'),
('внимание', 'attention'),
('достопримечательности', 'attraction'),
('власть', 'authority'),
('назад', 'back'),
('баланс', 'balance'),
('основной', 'base'),
('поведение', 'behavior'),
('вера', 'belief'),
('рождение', 'birth'),
('частица', 'bit'),
('укус', 'bite'),
('кровь', 'blood'),
('удар', 'blow'),
('тело', 'body'),
('медь', 'brass'),
('хлеб', 'bread'),
('дыхание', 'breath'),
('брат', 'brother'),
('здание', 'building'),
('ожог', 'burn'),
('взрыв', 'burst'),
('бизнес', 'business'),
('масло', 'butter'),
('сумка', 'bag'),
('мяч', 'ball'),
('банк', 'bank'),
('бассейн', 'basin'),
('корзина', 'basket'),
('ванна', 'bath'),
('кровать', 'bed'),
('пчела', 'bee'),
('колокольчик', 'bell'),
('ягода', 'berry'),
('птица', 'bird'),
('лезвие', 'blade'),
('доска', 'board'),
('лодка', 'boat'),
('кость', 'bone'),
('книга', 'book'),
('ботинок', 'boot'),
('бутылка', 'bottle'),
('коробка', 'box'),
('мальчик', 'boy'),
('мозг', 'brain'),
('тормоз', 'brake'),
('ветвь', 'branch'),
('кирпич', 'brick'),
('мост', 'bridge'),
('щётка', 'brush'),
('ведро', 'bucket'),
('луковица', 'bulb'),
('кнопка', 'button'),
('ребёнок', 'baby'),
('пирог', 'cake'),
('камера', 'camera'),
('карта', 'card'),
('везти', 'cart'),
('вагон', 'carriage'),
('кот', 'cat'),
('цепь', 'chain'),
('сыр', 'cheese'),
('сундук', 'chest'),
('подбородок', 'chin'),
('церковь', 'church'),
('круг', 'circle'),
('часы', 'clock'),
('облако', 'cloud'),
('пальто', 'coat'),
('воротник', 'collar'),
('расчёсывать', 'comb'),
('шнур', 'cord'),
('корова', 'cow'),
('чашка', 'cup'),
('занавес', 'curtain'),
('подушка', 'cushion'),
('собака', 'dog'),
('дверь', 'door'),
('утечка', 'drain'),
('ящик', 'drawer'),
('капля', 'drop'),
('ухо', 'ear'),
('яйцо', 'egg'),
('двигатель', 'engine'),
('глаз', 'eye'),
('лицо', 'face'),
('ферма', 'farm'),
('перо', 'feather'),
('палец', 'finger'),
('рыба', 'fish'),
('флаг', 'flag'),
('пол', 'floor'),
('муха', 'fly'),
('нога', 'foot'),
('домашняя птица', 'fowl'),
('структура', 'frame'),
('лететь', 'fly'),
('сад', 'garden'),
('девочка', 'girl'),
('перчатка', 'glove'),
('коза', 'goat'),
('оружие', 'gun'),
('волосы', 'hair'),
('молоток', 'hammer'),
('рука', 'hand'),
('шляпа', 'hat'),
('голова', 'head'),
('сердце', 'heart'),
('крюк', 'hook'),
('рожок', 'horn'),
('лошадь', 'horse'),
('больница', 'hospital'),
('дом', 'house'),
('остров', 'island'),
('драгоценный камень', 'jewel'),
('чайник', 'kettle'),
('ключ', 'key'),
('колено', 'knee'),
('нож', 'knife'),
('узел', 'knot'),
('лист', 'leaf'),
('нога', 'leg'),
('библиотека', 'library'),
('линия', 'line'),
('губа', 'lip'),
('замок', 'lock'),
('карта', 'map'),
('спичка', 'match'),
('обезьяна', 'monkey'),
('луна', 'moon'),
('рот', 'mouth'),
('мускул', 'muscle'),
('ноготь', 'nail'),
('шея', 'neck'),
('игла', 'needle'),
('нерв', 'nerve'),
('сеть', 'net'),
('нос', 'nose'),
('орех', 'nut'),
('офис', 'office'),
('апельсин', 'orange'),
('духовка', 'oven'),
('пакет', 'parcel'),
('ручка', 'pen'),
('карандаш', 'pencil'),
('картина', 'picture'),
('свинья', 'pig'),
('булавка', 'pin'),
('труба', 'pipe'),
('самолёт', 'plane'),
('пластина', 'plate'),
('плуг', 'plow'),
('карман', 'pocket'),
('горшок', 'pot'),
('картофель', 'potato'),
('тюрьма', 'prison'),
('насос', 'pump'),
('рельс', 'rail '),
('крыса', 'rat '),
('квитанция', 'receipt '),
('прут', 'rod '),
('крыша', 'roof '),
('корень', 'root '),
('парус', 'sail '),
('школа', 'school '),
('ножницы', 'scissors '),
('винт', 'screw '),
('семя', 'seed '),
('овцы', 'sheep '),
('полка', 'shelf '),
('корабль', 'ship '),
('рубашка', 'shirt '),
('ботинок', 'shoe '),
('кожа', 'skin'),
('юбка', 'skirt'),
('змея', 'snake'),
('лопата', 'spade'),
('губка', 'sponge'),
('ложка', 'spoon'),
('весна', 'spring'),
('квадрат', 'square'),
('печать', 'stamp'),
('звезда', 'star'),
('станция', 'station'),
('стебель', 'stem'),
('палка', 'stick'),
('снабжать', 'stocking'),
('живот', 'stomach'),
('магазин', 'store'),
('улица', 'street'),
('солнце', 'sun'),
('стол', 'table'),
('хвост', 'tail'),
('нить', 'thread'),
('горло', 'throat'),
('листать', 'thumb'),
('билет', 'ticket'),
('палец', 'toe'),
('язык', 'tongue'),
('зуб', 'tooth'),
('город', 'town'),
('поезд', 'train'),
('поднос', 'tray'),
('дерево', 'tree'),
('брюки', 'trousers'),
('стена', 'wall'),
('часы', 'watch'),
('колесо', 'wheel'),
('кнут', 'whip'),
('свист', 'whistle'),
('окно', 'window'),
('крыло', 'wing'),
('провод', 'wire'),
('червь', 'worm')
]
#Образование
words_e = [
('детский садик', 'kindergarten'),
('школа', 'school'),
('начальная школа', 'primary school'),
('средняя школа', 'secondary school'),
('лицей', 'lyceum'),
('гимназия', 'gymnasium'),
('школа-интернат', 'boarding school'),
('учитель', 'teacher'),
('школьники', 'schoolchildren'),
('урок', 'lesson'),
('ученик', 'pupil'),
('прогуливать уроки', 'to miss school'),
('пропуск', 'truancy'),
('программа обучения', 'curriculum'),
('объяснять', 'to explain'),
('спрашивать', 'to ask'),
('указать на ошибку', 'to make a mistake'),
('исправить ошибку', 'to correct a mistake'),
('контролировать', 'to test'),
('поставить оценку', 'to give a mark'),
('откликнуться', 'to respond'),
('отвечать', 'to answer'),
('писать контрольную', 'to write a test'),
('переписывать', 'to copy'),
('писать', 'to write'),
('студент', 'student'),
('читать', 'to read'),
('подчеркивать', 'to underline'),
('иллюстрировать', 'to illustrate'),
('описывать', 'to describe'),
('пересказывать', 'to retell'),
('читать на память', 'to recite'),
('приготавливать', 'to prepare'),
('считать', 'to calculate'),
('решать задачи', 'to do sums'),
('помнить', 'to remember'),
('помнить', 'to reminde'),
('помнить', 'to recall'),
('решать', 'to decide'),
('думать', 'to think'),
('обсуждать', 'to discuss'),
('отсутствовать', 'to be absent'),
('обучать', 'to teach'),
('давать образование', 'to educate'),
('учиться', 'to learn'),
('учить наизусть', 'to learn by heart'),
('изучать', 'to study'),
('лучший ученик', 'top pupil'),
('второгодник', 'repeater'),
('неуч', 'bright'),
('быть на занятиях', 'to be at school'),
('букварь', 'abc-book'),
('учебник', 'text book'),
('', 'book mark'),
('тетрадь', 'exercise-book'),
('тетрадь в клетку', 'a squared exercise-book'),
('тетрадь в линейку', 'lined exercise-book'),
('блокнот', 'note-pad'),
('блокнот', 'writing-pad'),
('черноовик', 'a rough copy'),
('линейка', 'ruler'),
('логарифмическая линейка', 'slide-ruler'),
('дневник', 'diary'),
('ранец', 'satchel'),
('поля в тетради', 'margin'),
('журнал', 'register'),
('компьютер', 'computer'),
('калькулятор', 'calculator'),
('портфель', 'school bag'),
('считать', 'to calculate'),
('клей', 'glue'),
('вырезать', 'to cut out'),
('звонок', 'bell'),
('звонить', 'to ring'),
('школа', 'school'),
('глобус', 'terrestrial globe'),
('скрепка', 'paper-clips'),
('кнопка', 'pin'),
('бумага', 'paper'),
('картон', 'paste-board'),
('лист', 'sheet'),
('альбом', 'album'),
('рисовать', 'to draw'),
('рисунок', 'drawing'),
('палитра', 'palette'),
('краска', 'paint'),
('кисточка', 'brush'),
('карандаш', 'pencil'),
('ручка', 'pen'),
('чернильная ручка', 'fountain-pen'),
('шариковая ручка', 'ball-point-pen'),
('писать', 'to write'),
('цветные карандаши', 'coloured pencils'),
('фломастер', 'felt-tip-pen'),
('чернила', 'ink'),
('кусочек мела', 'piece of chalk'),
('точилка', 'pencil sharpener'),
('пенал', 'pencil case'),
('резинка', 'an eraser'),
('стирать', 'to rub out'),
('математика', 'Maths'),
('алгебра', 'Algebra'),
('геометрия', 'Geometry'),
('физика', 'Physics'),
('химия', 'Chemistry'),
('биология', 'Biology'),
('ботаника', 'Botany'),
('география', 'Geography'),
('история', 'History'),
('литература', 'Literature'),
('родной', 'Native'),
('иностранный язык', 'Foreign language'),
('английский', 'English'),
('русский', 'Russian'),
('украинский', 'Ukrainian'),
('французский', 'French'),
('немецкий', 'German'),
('лингвистика', 'Linguistics'),
('изо', 'Art'),
('черчение', 'Technical drawing'),
('информатика', 'Computering'),
('физкультура', 'Sport'),
('труд (урок)', 'Labour training'),
('класс', 'classroom'),
('школьная доска', 'blackboard'),
('парта', 'desk'),
('наглядные пособия', 'visual aids'),
('одноклассник', 'classmate'),
('староста', 'monitor'),
('учитель', 'teacher'),
('преподавательский состав', 'teaching staff'),
('вестибюль', 'entrance hall'),
('актовый зал', 'assembly hall'),
('гимнастический зал', 'gymnasium'),
('стадион', 'stadium'),
('учительская', 'staff room'),
('выставочный зал', 'display room'),
('библиотека', 'library'),
('раздевалка', 'cloak room'),
('врач', 'doctor'),
('столовая', 'dining room'),
('столярные мастерские', 'wood work'),
('слесарные мастерские', 'metal work'),
('кабинет домоводства', 'domestic science'),
('кабинет рукоделия', 'needle work'),
('школьный сад', 'school garden'),
('школьный участок', 'school plot'),
('урок', 'lesson'),
('начать урок', 'begin the lesson'),
('Урок окончен', 'The lesson is over'),
('открытый урок', 'a demonstration lesson'),
('лекция', 'lecture'),
('занятия', 'classes'),
('оценка', 'mark'),
('оценка', 'grade'),
('сдавать экзамен (тест)', '(to) take a test'),
('сдать экзамен (тест)', '(to) pass a test'),
('провалить экзамен (тест)', '(to)fail a test'),
('проводить экзамен (тест)', ' (to) administer a test'),
('профессионально-техническое училище', 'vocational school'),
('художественное училище', 'art school (college)'),
('техникум', 'technical school'),
('педагогическое училище', 'college of education'),
('ректор', 'Rector (President)'),
('проректор', 'Vice- rector'),
('Декан', 'Dean'),
('зам. Декана', 'Assistant dean'),
('профессор', 'Full professor'),
('доцент', 'Associate professor'),
('старший преподаватель', 'Assistant professor'),
('преподаватель', 'Instructor'),
('ст. Лаборант кафедры (секретарь)', 'Department secretary'),
('лаборант кафедры (помощник секретаря)', 'Assistant secretary'),
('лаборант ', ' Lab (oratory) assistant	'),
('куратор', 'Tutor'),
('ученый совет университета', 'Senate'),
('факультет', 'Department'),
('Cовет факультета', 'School board'),
('кафедра', 'Department board'),
('заведующий кафедры', 'head of (the) department'),
('заседание кафедры', 'department meeting'),
('отделение', 'department'),
('дневное отделение (стационар)', 'full-time department'),
('вечернее отделение', 'part-time department'),
('вечерние курсы', 'evening courses'),
('заочное отделение', 'correspondence department'),
('отделение дистанционного обучения', 'distant learning department'),
('факультет', 'faculty'),
('штат', 'staff'),
('научно-исследовательский институт', 'research institute'),
('исследователь', 'researcher'),
('ученый в отрасли естественных наук', 'scientist'),
('ученый в отрасли гуманитарных наук', 'scholar'),
('учебный год', 'academic year'),
('учебный год', 'session'),
('семестр', 'term'),
('зимняя или весенняя экзаменационная сессия', 'mid-sessional exam (inations)'),
('летняя экзаменационная сессия', 'sessional exam (inations)'),
('рождественские каникулы', 'Christmas vacation'),
('пасхальные каникулы', 'Easter vacation'),
('летние каникулы', 'summer vacation'),
('лекция', 'lecture'),
('практическое занятие', 'class'),
('семинар', 'seminar'),
('консультация', 'tutorial'),
('первокурсник', 'fresher'),
('второкурсник', 'sophomore'),
('младшекурсник', 'junior'),
('старшекурсник', 'senior'),
('выпускник', 'graduator'),
('аспирант', 'post-graduate'),
('аспирантура', 'graduate-school'),
('наука', 'science'),
('научное исследование', 'scientific research'),
('исследовать', 'to investigate'),
('ученый', 'scientist'),
('хорошо известный', 'well-known'),
('зачет', 'test'),
('зачетка', 'student’s record book'),
('экзамен', 'exam'),
('государственный экзамен', 'degree exam'),
('общежитие', 'student hostel'),
('стипендия', 'grant'),
('именная стипендия', 'scholarship'),
('премия', 'award'),
('квалификация', 'qualification'),
('специальность', 'major'),
('специальность', 'speciality'),
]
#Еда
words_f = [
('суп', 'soup'),
('полезно', 'agrees with'),
('миндаль', 'almond'),
('аппетит', 'appetite'),
('яблоко', 'apple'),
('абрикос', 'apricot'),
('спаржа', 'asparagus'),
('ассорти', 'assortment'),
('завтрак', 'breakfast'),
('ужин', 'dinner'),
('яичница с беконом', 'bacon and eggs'),
('запекать', 'bake'),
('запеченный', 'baked'),
('консервированная фасоль', 'baked beans'),
('банан', 'banana'),
('дуршлаг', 'basket'),
('фасоль', 'beans'),
('говядина', 'beef'),
('бифштекс', 'beefsteak'),
('свекла', 'beet'),
('ягода', 'berry'),
('напиток', 'beverage'),
('черника', 'bilberry'),
('печенье', 'biscuits'),
('горький', 'bitter'),
('маслина', 'black olive'),
('ежевика', 'blackberry'),
('варить', 'boil'),
('отварной', 'boiled'),
('топленое масло', 'boiled butter'),
('вареное яйцо', ''),
('бутылочная открывалка', ''),
('миска', 'bowl'),
('хлеб', 'bread'),
('хлеб с маслом', 'bread and butter'),
('хлеб с сыром', 'bread and cheese'),
('панировочные сухари', 'bread-crumbs'),
('лещ', 'bream'),
('черный хлеб', 'brown bread'),
('гречневая крупа', 'buckwheat'),
('кекс', 'bun'),
('сливочное масло', 'butter'),
('масленка', 'butter-dish'),
('капуста', 'cabbage'),
('кафе', 'cafe'),
('кафетерий', 'cafeteria'),
('торт', 'cake'),
('карамель', 'candy'),
('консервированный', 'canned'),
('столовая', 'canteen'),
('карп', 'carp'),
('морковь', 'carrot'),
('утятница', 'casserole'),
('цветная капуста', 'cauliflower'),
('икра', 'caviar'),
('сыр', 'cheese'),
('ватрушка', 'cheese-cake'),
('черешня', 'cherry'),
('цыпленок', 'chicken'),
('окорочка', 'chicken quarters'),
('куриный бульон', 'chicken-broth'),
('жаренный картофель', 'chips'),
('шоколад', 'chocolate'),
('шоколадные конфеты', ''),
('отбивная котлета', ''),
('корица', 'cinnamon'),
('бульон', 'clear soup'),
('треска', 'cod'),
('кофеварка', 'coffee maker'),
('кофемолка', 'coffee-grinder'),
('кофейник', 'coffee-pot'),
('буженина', 'cold boiled pork'),
('кондитерская', 'confectionery'),
('повар', 'cook'),
('готовить пищу', 'cook'),
('поваренная книга', 'cookery-book'),
('штопор', 'cork screw'),
('кукуруза', 'corn'),
('кукурузный початок', 'corn-cob'),
('кукурузные хлопья', 'corn-flake'),
('творог', 'cottage cheese'),
('краб', 'crab'),
('клюква', 'cranberry'),
('сливки', 'cream'),
('чипсы', 'crisps'),
('крошки', 'crumbs'),
('огурец', 'cucumber'),
('чашка', 'cup'),
('смородина', 'currant'),
('очень вкусный', 'delicious'),
('десерт', 'dessert'),
('десертная ложка', 'dessert-spoon	'),
('диета', 'diet'),
('укроп', 'dill'),
('обедать', 'dine'),
('обед', 'dinner'),
('мелкая тарелка', 'dinner plate'),
('вредно', 'disagrees with'),
('блюдо', 'dish'),
('сушилка для посуды', 'dish rack'),
('машина для мойки посуды', 'dishwasher'),
('тесто', 'dough'),
('плохо выпеченный', 'dough-baked'),
('пончик', 'doughnut'),
('гарнир', 'dressing'),
('пить', 'drink'),
('утка', 'duck'),
('клецка', 'dumpling'),
('кушать', 'eat'),
('съедобный', 'eatable'),
('угорь', 'eel'),
('яйцо', 'egg'),
('сэндвич с яйцом', 'egg sandwich'),
('баклажан', 'egg-plant'),
('наслаждаться', 'enjoy'),
('жирный', 'fatty'),
('кормить', 'feed'),
('питаться', 'feed on'),
('инжир', 'fig'),
('начинка', 'filling'),
('рыба', 'fish'),
('рыбное блюдо', 'fish dish'),
('пресный (только о пище)', 'flavourless'),
('мука', 'flour'),
('пища', 'food'),
('на десерт', 'for dessert'),
('на обед', 'for dinner'),
('на ужин', 'for supper'),
('вилка', 'fork'),
('свежий', 'fresh'),
('парное молоко', 'fresh milk'),
('жареный', 'fried'),
('яичница-глазунья', 'fried eggs'),
('фрукты', 'fruit'),
('жарить', 'fry'),
('сковородка', 'frying pan'),
('дичь', 'game'),
('чеснок', 'garlic'),
('гуси', 'geese'),
('имбирь', 'ginger'),
('имбирный пряник', 'gingerbread'),
('рюмка', 'glass'),
('стакан', 'glass'),
('стакан молока', 'glass of milk'),
('гусь', 'goose'),
('крыжовник', 'gooseberry'),
('грейпфрут', 'grapefruit'),
('виноград', 'grapes'),
('натереть', 'grate'),
('терка', 'grater'),
('мясная подлива', 'gravy'),
('неспелый', 'green'),
('молодой сыр', 'green cheese'),
('оливка', 'green olive'),
('окорок', 'ham'),
('ветчина', 'ham'),
('гамбургер', 'hamburger'),
('яйцо вкрутую', 'hard-boiled egg	'),
('перекусить', 'have a bite'),
('рябчик', 'hazel-hen'),
('положить себе (на тарелку)', 'help oneself to'),
('порция', 'helping'),
('курица', 'hen'),
('сельдь', 'herring'),
('мед', 'honey'),
('медовый пряник', 'honeycake'),
('хрен', 'horse-radish'),
('голодный', 'hungry'),
('ломоть', 'hunk'),
('мороженое', 'ice-cream'),
('кипятильник', 'immersion heater'),
('варенье', 'jam'),
('банка', 'jar'),
('желе', 'jelly'),
('кувшин', 'jug'),
('соковыжималка', 'juice extractor'),
('придерживаться диеты', 'keep to a diet'),
('чайник', 'kettle'),
('почки', 'kidneys'),
('кухонные весы', 'kitchen scale'),
('замешивать', 'knead'),
('нож', 'knife'),
('черпак', 'ladle'),
('накрывать на стол', 'lay the table'),
('постный (о мясе)', 'lean'),
('заквашивать', 'leaven'),
('лимон', 'lemon'),
('лимоновыжималка', 'lemon squeezer'),
('салат-латук', 'lettuce'),
('крышка', 'lid'),
('печенка', 'liver'),
('батон', 'loaf'),
('омар', 'lobster'),
('второй завтрак', 'lunch'),
('скумбрия', 'mackerel'),
('маргарин', 'margarine'),
('повидло', 'marmalade'),
('мармелад', 'marmalade'),
('картофельное пюре', 'mashed potatoes'),
('майонез', 'mayonnaise'),
('прием пищи', 'meal'),
('мясо', 'meat'),
('тефтели', 'meat balls'),
('дыня', 'melon'),
('растопить', 'melt'),
('меню', 'menu'),
('молоко', 'milk'),
('молочный коктейль', 'milk shake'),
('бидон', 'milk-can'),
('молочник', 'milk-jug'),
('пшено', 'millet'),
('мясной фарш', 'mince meat'),
('мясорубка', 'mincing-maching'),
('смешивать', 'to mix'),
('миксер', 'mixer'),
('кружка', 'mug'),
('гриб', 'mushroom'),
('горчица', 'mustard'),
('горчичница', 'mustard-pot'),
('баранина', 'mutton'),
('лапша', 'noodle'),
('питательный', 'nourishing'),
('орех', 'nut'),
('щипцы для орехов', 'nutcrackers'),
('овес', 'oats'),
('растительное масло', 'oil'),
('омлет', 'omelette'),
('на диете', 'on a diet'),
('лук', 'onion'),
('апельсин', 'orange'),
('заказывать', 'order'),
('пережаренный', 'overdone'),
('устрица', 'oyster'),
('блины', 'pancakes'),
('петрушка', 'parsley'),
('куропатка', 'partridge'),
('передавать', 'pass'),
('персик', 'peach'),
('арахис', 'peanut'),
('груша', 'pear'),
('горох', 'peas'),
('кожура', 'peel'),
('перец', 'pepper'),
('перечница', 'pepper-box'),
('окунь', 'perch'),
('фазан', 'pheasant'),
('солить', 'pickle'),
('пирог', 'pie'),
('щука', 'pike'),
('ананас', 'pine-apple'),
('пикантный', 'piquant'),
('фисташка', 'pistachio'),
('камбала', 'plaice'),
('тарелка', 'plate'),
('слива', 'plum'),
('гранат', 'pomegranate'),
('свинина', 'pork'),
('овсяная каша', 'porridge'),
('горшочек', 'pot'),
('картофель', 'potatoes'),
('домашняя птица', 'poultry'),
('сахарная пудра', 'powdered sugar'),
('предпочитать', 'prefer'),
('скороварка', 'pressure cooker'),
('плавленый сыр', 'processed cheese'),
('чернослив', 'prune'),
('пудинг', 'pudding'),
('тыква', 'pumpkin'),
('кролик', 'rabbit'),
('редис', 'radish'),
('изюм', 'raisin'),
('малина', 'raspberry'),
('рецепт', 'recipe'),
('закуска', 'refreshments'),
('ресторан', 'restaurant'),
('грудинка', 'ribs'),
('рис', 'rice'),
('кожура', 'rind'),
('спелый', 'ripe'),
('жаркое', 'roast'),
('жаренный цыпленок', 'roast chicken'),
('булочка', 'roll'),
('скалка', 'rolling-pin'),
('сухарь', 'rusk'),
('ржаной', 'rye'),
('салат', 'salad'),
('лосось', 'salmon'),
('соль', 'salt'),
('солонка', 'salt-cellar'),
('соленый', 'salty'),
('бутерброд', 'sandwich'),
('сардина', 'sardine'),
('кастрюля', 'saucepan'),
('блюдце', 'saucer'),
('кислая капуста', 'sauerkraut'),
('сосиска', 'sausage'),
('приправа', 'seasoning'),
('манная крупа', 'semolina'),
('обслуживать', 'serve'),
('сом', 'sheat-fish'),
('скорлупа', 'shell'),
('креветка', 'shrimp'),
('просеивать', 'sift'),
('тонкий кусок', 'slice'),
('копченый', 'smoked'),
('легкая закуска', 'snack'),
('буфет', 'snack bar'),
('зернистая икра', 'soft caviar'),
('яйцо всмятку', 'soft-boiled egg'),
('суп', 'soup'),
('супница', 'soup-tureen'),
('кислый', 'sour'),
('вишня', 'sour cherry'),
('сметана', 'sour cream'),
('простокваша', 'sour milk'),
('рассол', 'souse'),
('пряность', 'spice'),
('острый', 'spicy'),
('шпинат', 'spinach'),
('портиться', 'spoil'),
('бисквит', 'sponge'),
('ложка', 'spoon'),
('килька', 'sprat'),
('черствый (о хлебе)', 'stale'),
('обрабатывать на пару', 'steam'),
('тушить', 'stew'),
('земляника', 'strawberry'),
('острый сыр', 'strong cheese'),
('фаршировать', 'stuff'),
('фаршированный', 'stuffed'),
('осетрина', 'sturgeon'),
('сытный', 'substantial'),
('сочный', 'succulent'),
('сахар', 'sugar'),
('сахарница', 'sugar-basin'),
('щипцы для сахара', 'sugar-tongs'),
('ужин', 'supper'),
('сладкий', 'sweet'),
('конфеты', 'sweets'),
('мандарин', 'tangerine'),
('фруктовый пирог', 'tart'),
('пробовать на вкус', 'taste'),
('безвкусный', 'tasteless'),
('вкусный', 'tasty'),
('заварочный чайник', 'teapot'),
('чайная ложка', 'teaspoon'),
('нежный (о мясе)', 'tender'),
('термос', 'thermos jug	'),
('густой суп', 'thick soup'),
('испытывающий жажду', 'thirsty'),
('таймер', 'timer'),
('консервная банка', 'tin'),
('консервный нож', 'tin opener'),
('рыбные консервы', 'tinned fish'),
('тостер', 'toaster'),
('гренки', 'toasts'),
('помидор', 'tomato'),
('жесткий', 'tough'),
('поднос', 'tray'),
('угощать', 'treat to'),
('форель', 'trout'),
('индейка', 'turkey'),
('репа', 'turnip'),
('недожаренный', 'underdone'),
('малосольный', 'undersalted'),
('пресный (о тесте)', 'unleavened'),
('ваниль', 'vanilla'),
('телятина', 'veal'),
('овощ', 'vegetable'),
('кабачок', 'vegetable marrow'),
('овощи', 'vegetables'),
('уксус', 'vinegar'),
('официант', 'waiter'),
('официантка', 'waitress'),
('грецкий орех', 'walnut'),
('арбуз', 'water melon'),
('белый хлеб', 'white bread'),
('белок', 'white of an egg'),
('хлеб с отрубями', 'wholemeal bread'),
('дрожжи', 'yeast'),
('йогурт', 'yogurt'),
('желток', 'yolk')
]
#Одежда
words_w = [
('блузка', 'blouse'),
('батинки', 'boot'),
('браслет', 'bracelet'),
('брюки', 'trousers'),
('булавка', 'pin'),
('воротник', 'collar'),
('галстук', 'tie'),
('джинсы', 'jeans'),
('длинный', 'long'),
('духи', 'perfume'),
('духи', 'scent'),
('жилет', 'waistcoat'),
('зонтик', 'umbrella'),
('карман', 'pocket'),
('кожа', 'leather'),
('кольцо', 'ring'),
('короткий', 'short'),
('костюм', 'suit'),
('кроссовки', 'trainers'),
('купальный костюм', 'swimsuit'),
('куртка', 'jacket'),
('лифчик', 'bra'),
('мех', 'fur'),
('модный', 'fashionable'),
('мягкий', 'soft'),
('надевать', 'to put on	'),
('нейлон', 'nylon'),
('нитка', 'thread'),
('носовой платок', 'handkerchief'),
('носок', 'sock'),
('обувь', 'footwear'),
('одеваться', 'to get dressed'),
('одежда', 'clothes'),
('очки', 'glasses'),
('пальто', 'coat'),
('переодеваться', 'to get changed'),
('перчатка', 'glove'),
('пижама', 'pyjamas'),
('плавки', 'swimming trunks'),
('платье', 'dress'),
('плащ', 'raincoat'),
('подкладка', 'lining'),
('портфель', 'briefcase'),
('просторный', 'loose'),
('пуговица', 'button'),
('пятно', 'stain'),
('развязывать', 'to untie'),
('развязывать ', 'to undo'),
('раздеваться', 'to get undressed'),
('размер', 'size'),
('расстёгивать', 'to unfasten'),
('расстегнуть', 'to unbutton'),
('рвать', 'to tear'),
('ремень', 'belt'),
('рубашка', 'shirt'),
('рукав', 'sleeve'),
('серьга', 'earring'),
('снимать', 'to take off'),
('солнцезащитные очки', 'sunglasses'),
('тесный', 'tight'),
('спица', 'knitting needle'),
('ткань', 'fabric'),
('ткань', 'cloth'),
('трусы', 'underpants'),
('трусы', 'knickers'),
('туфля', 'shoe'),
('туфля', 'slipper'),
('футболка', 't-shirt'),
('хлопок', 'cotton'),
('хорошо сидеть', 'to fit (well)'),
('цвет', 'colour'),
('цепочка', 'necklace'),
('цепочка', 'chain'),
('чинить', 'to repair'),
('чулок', 'stocking'),
('шарф', 'scarf'),
('швейная машина', 'sewing machine'),
('шёлк', 'silk'),
('шерсть', 'wool'),
('шить', 'to sew'),
('шляпа', 'hat'),
('шнурок', 'lace'),
('шорты', 'shorts'),
('шуба', 'fur coat'),
('элегантный', 'elegant'),
('юбка', 'skirt'),
('ювелирные изделия', 'jewellery'),
('униформа', 'uniform'),
('спецодежда', 'protective clothing'),
('головной убор', 'headgear'),
('нижнее белье', 'underwear'),
('спортивная одежда', 'sportswear'),
('купальный костюм', 'swimwear'),
('ночное белье', 'sleepwear'),
('одеяние', 'attire'),
('мода', 'fashion'),
('стиль', 'style'),
('мода', 'vogue'),
('высокая мода', 'haute couture'),
('Верхняя одежда', 'Outer garments'),
('теплое пальто', 'warm coat'),
('дубленка', 'sheepskin coat'),
('парка', 'parka'),
('детский зимний комбинезон', 'snowsuit'),
('пальто', 'topcoat'),
('пальто', 'overcoat'),
('плащ', 'raincoat'),
('дождевик', 'raincoat'),
('непромокаемый плащ', 'slicker'),
('кожанка', 'leather jacket'),
('короткая куртка', 'bomber jacket'),
('полупальто', 'car coat'),
('ветровка', 'windbreaker'),
('ветровка', 'windcheater'),
('спортивная куртка', 'sports jacket'),
('повседневная одежда', 'casual dress'),
('летнее платье', 'summer dress	'),
('вечернее платье', 'cocktail dress	'),
('деловой костюм', 'business suit'),
('свитер', 'sweater'),
('свитер', 'jersey'),
('куртка', 'jacket'),
('жилет', 'vest'),
('рубашка', 'shirt'),
('туника', 'tunic'),
('юбка', 'skirt'),
('брюки', 'pants'),
('широкие брюки', 'slacks'),
('джинсы', 'denims'),
('шорты', 'shorts'),
('бикини', 'bikini'),
('смокинг', 'tuxedo'),
('фрак', 'tuxedo'),
('фрак', 'tail coat'),
('колготки', 'pantyhose'),
('колготки', 'tights'),
('лосины', 'leggings'),
('чулки', 'stockings'),
('пижама', 'pajamas'),
('халат', 'robe'),
('без воротника', 'collarless'),
('круглый вырез', 'crew neck'),
('манжеты', 'cuffs')
]
#Путешесвия
words_t = [
('авиакомпания', 'airlines'),
('автобус', 'bus'),
('агентство', 'agency'),
('аэропорт', 'airport'),
('багаж', 'baggage'),
('багаж', 'luggage'),
('бензин', 'gas'),
('бензин', 'gasoline'),
('билет', 'ticket'),
('валюта', 'currency'),
('велосипед', 'bicycle'),
('взлетать', 'to take off'),
('виза', 'visa'),
('внутренний туризм', 'domestic tourism'),
('вокзал', 'railway station'),
('временная миграция', 'temporary migration'),
('говорить по-английски', 'to speak English'),
('город', 'town'),
('город', 'city'),
('гостевой дом', 'guest house'),
('гостиница', 'hotel'),
('гостиничная сеть', 'hotel chain'),
('граница', 'border'),
('достопримечательности', 'attractions'),
('европейские страны', 'European countries'),
('ежегодный отпуск', 'annual vacation'),
('ехать за границу', 'to go abroad'),
('железная дорога', 'railway'),
('за границей', 'abroad'),
('загорать', 'to get a suntan'),
('загорелый', 'tanned'),
('загорелый', 'bronzed'),
('граница', 'frontier'),
('Западная Европа', 'Western Europe'),
('индустрия туризма', 'tourist industry'),
('иностранец', 'foreigner'),
('иностранный', 'foreign'),
('каникулы', 'vacation'),
('карта', 'map'),
('корабль', 'ship'),
('курорт', 'resort'),
('лечиться на водах', 'take the waters'),
('лёгкий', 'light'),
('маршрут', 'route'),
('машина', 'car'),
('международный туризм', 'international tourism'),
('минеральные источники', 'spa'),
('мероприятия', 'arrangements'),
('мотоцикл', 'motorcycle'),
('направление', 'direction'),
('небольшой отель', 'inn'),
('нетронутая природа', 'unspoiled nature'),
('номер', 'room'),
('окружающая среда', 'environment'),
('оплачиваемый отпуск', 'paid vacations'),
('островное государство', 'island state'),
('отдых', 'rest'),
('отдыхать', 'to be on vacation'),
('открытка', 'postcard'),
('отправляться', 'to set out'),
('отпуск', 'vacation'),
('отпуск', 'leave'),
('каникулы', 'vacation'),
('палатка', 'tent'),
('пароход', 'steamship'),
('паспорт', 'passport'),
('перевозка', 'transportation'),
('пляж', 'beach'),
('побережье', 'seaside'),
('поезд', 'train'),
('поездка', 'journey'),
('поездка', 'trip'),
('поездка', 'tour'),
('поездка по путевке', 'package tour'),
('популярный курорт', 'popular destination'),
('порт', 'port'),
('порт', 'harbor'),
('поток туристов', 'flow of tourists'),
('прибывать', 'to arrive'),
('приземляться', 'to land'),
('провожать', 'to see off'),
('путешествие', 'journey'),
('путешествие', 'voyage'),
('путешествия для отдыха', 'traveling for leisure'),
('путешествовать', 'to travel'),
('развлечение', 'recreation'),
('рюкзак', 'backpack'),
('садиться (на что)', 'to get on'),
('самолёт', 'plane'),
('скучать', 'to miss'),
('спасательный жилет', 'life-jacket'),
('Средиземноморье', 'Mediterranean'),
('столица', 'capital'),
('страна', 'country'),
('странный', 'strange'),
('сувенирные магазины', 'souvenir shops'),
('сходить (с)', 'to get off'),
('такси', 'taxi'),
('трамвай', 'streetcar'),
('трамвай', 'trolley'),
('трамвай', 'tram'),
('туризм', 'tourism'),
('туризм', 'traveling'),
('чемодан', 'suitcase'),
('экзотический', 'exotic'),
('экотуризм', 'eco-tourism'),
('юг', 'the South'),
]